##### KKT MONITORING#####################
UserParameter=kkt.rnm[*],cscript.exe "C:\zabbix\scripts\kktatol.js" 5 //nologo
UserParameter=kkt.fnnumber[*],cscript.exe "C:\zabbix\scripts\kktatol.js" 6 //nologo
UserParameter=kkt.datenotsenddoc[*],cscript.exe "C:\zabbix\scripts\kktatol.js" 4 //nologo
UserParameter=kkt.datefnend[*],cscript.exe "C:\zabbix\scripts\kktatol.js" 7 //nologo